force-app/main/default/objects/Account/fields/Territory__c.field-meta.xml
<CustomField>
    <fullName>Territory__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>assigned territory</description>
    <label>Territory</label>
    <referenceTo>Territory__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Territory__c/Territory__c.object-meta.xml
<CustomObject>
    <label>Territory</label>
    <nameField>
        <label>Territory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territories</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/TerritoryUser__c/TerritoryUser__c.object-meta.xml
<CustomObject>
    <description>link Territory &lt;-&gt; User</description>
    <label>TerritoryUser</label>
    <nameField>
        <displayFormat>TU-{00000}</displayFormat>
        <label>TerritoryUser Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>TerritoryUsers</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/TerritoryUser__c/fields/Territory__c.field-meta.xml
<CustomField>
    <fullName>Territory__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>link to territory</description>
    <label>Territory</label>
    <referenceTo>Territory__c</referenceTo>
    <relationshipLabel>Territories</relationshipLabel>
    <relationshipName>TerritoryUsers</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TerritoryUserHandler.cls
public with sharing class TerritoryUserHandler {
    
    public static void addTUserAccess(List<TerritoryUser__c> tUsers) {
        List<Territory__c> territories = new List<Territory__c> ();
        for (TerritoryUser__c tUser : tUsers) {
            territories.add(new Territory__c( Id = tUser.Territory__c));
        }
        territories = TerritoryBasedSharing.findSubTerritories(territories);
        List<Account> accounts = [select Id,Territory__c from Account where Territory__c in :territories];
        AccountHandler.addAccountAccess(accounts);
    }

    public static void removeTUserAccess(List<TerritoryUser__c> tUsers) {
        List<Territory__c> territories = new List<Territory__c> ();
        for (TerritoryUser__c tUser : tUsers) {
            territories.add(new Territory__c( Id = tUser.Territory__c));
        }
        territories = TerritoryBasedSharing.findSubTerritories(territories);
        List<Account> accounts = [select Id,Territory__c from Account where Territory__c in :territories];
        AccountHandler.removeAccountAccess(accounts);
    }
}