force-app/main/default/objects/Account/fields/Territory__c.field-meta.xml
<CustomField>
    <fullName>Territory__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>assigned territory</description>
    <label>Territory</label>
    <referenceTo>Territory__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Reference__c/Reference__c.object-meta.xml
<CustomObject>
    <description>custom account &lt;-&gt; contact relationship</description>
    <label>Reference</label>
    <nameField>
        <displayFormat>R-{0000}</displayFormat>
        <label>Reference Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>References</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Reference__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>link to account</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>References1</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Reference__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <description>link to contact</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>References1</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Territory__c/Territory__c.object-meta.xml
<CustomObject>
    <label>Territory</label>
    <nameField>
        <label>Territory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territories</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/ReferenceHandler.cls
public with sharing class ReferenceHandler {

    public static void addReferenceAccess(List<Reference__c> refs) {
        List<Reference__c> references = [select Account__r.Id,Account__r.Territory__c, Contact__r.Id from Reference__c where Id in :refs];
        List<Account> accounts = new List<Account>();
        for(Reference__c ref : references) {
             accounts.add(ref.Account__r);
        }
        AccountHandler.addAccountAccess(accounts);
    }
    
    public static void removeReferenceAccess(List<Reference__c> refs) {
        List<Reference__c> references = [select Account__r.Id,Account__r.Territory__c, Contact__r.Id from Reference__c where Id in :refs];
        List<Account> accounts = new List<Account>();
        for(Reference__c ref : references) {
             accounts.add(ref.Account__r);
        }
        AccountHandler.removeAccountAccess(accounts);
    }
}