force-app/main/default/objects/Account/fields/Territory__c.field-meta.xml
<CustomField>
    <fullName>Territory__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>assigned territory</description>
    <label>Territory</label>
    <referenceTo>Territory__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Reference__c/Reference__c.object-meta.xml
<CustomObject>
    <description>custom account &lt;-&gt; contact relationship</description>
    <label>Reference</label>
    <nameField>
        <displayFormat>R-{0000}</displayFormat>
        <label>Reference Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>References</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Reference__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>link to account</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>References1</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Reference__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <description>link to contact</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>References1</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Territory__c/Territory__c.object-meta.xml
<CustomObject>
    <label>Territory</label>
    <nameField>
        <label>Territory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territories</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Territory__c/fields/Parent__c.field-meta.xml
<CustomField>
    <fullName>Parent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Territory object is located in</description>
    <label>Parent</label>
    <referenceTo>Territory__c</referenceTo>
    <relationshipLabel>Territories</relationshipLabel>
    <relationshipName>Territories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TerritoryUser__c/TerritoryUser__c.object-meta.xml
<CustomObject>
    <description>link Territory &lt;-&gt; User</description>
    <label>TerritoryUser</label>
    <nameField>
        <displayFormat>TU-{00000}</displayFormat>
        <label>TerritoryUser Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>TerritoryUsers</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/TerritoryUser__c/fields/Territory__c.field-meta.xml
<CustomField>
    <fullName>Territory__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>link to territory</description>
    <label>Territory</label>
    <referenceTo>Territory__c</referenceTo>
    <relationshipLabel>Territories</relationshipLabel>
    <relationshipName>TerritoryUsers</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TerritoryUser__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>link to user</description>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipLabel>TerritoryUsers</relationshipLabel>
    <relationshipName>TerritoryUsers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TerritoryUserSharing.cls
public with sharing class TerritoryUserSharing {
    public static void AddSharing(List<TerritoryUser__c> tUserList) {
        List<Territory__c> territoriesToUpdate = getTerritoryHierarchy(tUserList);
        List<Account> accountsToUpdate = [select Id from Account where Territory__c in :territoriesToUpdate];
        List<AccountShare> accountShare = new List<AccountShare>();

        for (Account acc : accountsToUpdate) {
            AccountShare accShr = new AccountShare(
                AccountId = acc.Id,
                UserOrGroupId = tUserList[0].User__c, // FIXME: does not support multiple sales rep users
                AccountAccessLevel = 'Edit',
                ContactAccessLevel = 'Edit',
                OpportunityAccessLevel = 'None',
                CaseAccessLevel = 'None'
            );
            accountShare.add(accShr);
        }
        Database.SaveResult[] saveResults = Database.insert(accountShare,false);
        for(Database.SaveResult dsr : saveResults) {
            if (!dsr.isSuccess()) {
                for(Database.Error err : dsr.getErrors()) {
                    System.debug('ERROR: ' + err.getStatusCode() + ': ' + err.getMessage());
                    System.debug('Fields that affected this error: ' + err.getFields());
                }
            }
        }

        List<Contact> contacts = [select Id,Name from Contact where Id in (select Contact__c from Reference__c where Account__c in :accountsToUpdate)];
        List<ContactShare> contactShare = new List<ContactShare>();
        for (Contact cont : contacts) {
            ContactShare shr = new ContactShare(
                ContactId = cont.Id,
                UserOrGroupId = tUserList[0].User__c, // FIXME: does not support multiple sales rep users
                ContactAccessLevel = 'Edit'
            );
            contactShare.add(shr);
        }
        saveResults = Database.insert(contactShare,false);
        for(Database.SaveResult dsr : saveResults) {
            if (!dsr.isSuccess()) {
                for(Database.Error err : dsr.getErrors()) {
                    System.debug('ERROR: ' + err.getStatusCode() + ': ' + err.getMessage());
                    System.debug('Fields that affected this error: ' + err.getFields());
                }
            }
        }
    }

    public static void RemoveSharing() {
        User salesRep = [select Id,Name from User where Username = 'jdoe_salesrep@test.com'];
        List<Account> accountsToUpdate = [select Id from Account where Territory__c != null];
        List<Contact> contactsToUpdate = [select Id from Contact where Id in (select Contact__c from Reference__c where Account__c in :accountsToUpdate)];
        List<AccountShare> accountShare = [select Id from AccountShare where AccountId in :accountsToUpdate and UserOrGroupId = :salesRep.Id];
        List<ContactShare> contactShare = [select Id from ContactShare where ContactId in :contactsToUpdate and UserOrGroupId = :salesRep.Id];

        Database.DeleteResult[] deleteResults = Database.delete(accountShare,false);
        for(Database.DeleteResult ddr : deleteResults) {
            if (!ddr.isSuccess()) {
                for(Database.Error err : ddr.getErrors()) {
                    System.debug('ERROR: ' + err.getStatusCode() + ': ' + err.getMessage());
                    System.debug('Fields that affected this error: ' + err.getFields());
                }
            }
        }

        deleteResults = Database.delete(contactShare,false);
        for(Database.DeleteResult ddr : deleteResults) {
            if (!ddr.isSuccess()) {
                for(Database.Error err : ddr.getErrors()) {
                    System.debug('ERROR: ' + err.getStatusCode() + ': ' + err.getMessage());
                    System.debug('Fields that affected this error: ' + err.getFields());
                }
            }
        }
    }

    //Get assigned Territory and subordinates recursively
    private static List<Territory__c> getTerritoryHierarchy(List<TerritoryUser__c> tUserList) {
        List<Territory__c> topLevels = [select Id,Name from Territory__c where Id in (select Territory__c from TerritoryUser__c where Id in :tUserList)];
        List<Territory__c> territoriesToUpdate = new List<Territory__c>(topLevels);
        List<Territory__c> currentLevel= new List<Territory__c>(topLevels);
        Boolean isDone = false;
        while(!isDone) {
            currentLevel = [select Id,Name,Parent__c from Territory__c where Parent__c in :currentLevel];
            if (currentLevel.size() > 0) {
                territoriesToUpdate.addall(currentLevel);
            } else {
                isDone = true;
            }
        }
        return territoriesToUpdate;
    }
}